/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/kbm.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kbm.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 55.943]} rotation={[-Math.PI / 2, 0, 0]} scale={90.219}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-0.06, 0.795, -0.034]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube048_Mouse_0001.geometry} material={materials['Mouse.001']} />
            <mesh geometry={nodes.Keycap033_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.088, -0.018, 0.01]} />
            <mesh geometry={nodes.Keycap034_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.097, 0, 0.011]} />
            <mesh geometry={nodes.Keycap035_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.101, 0.018, 0.012]} />
            <mesh geometry={nodes.Keycap036_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.129, 0.037, 0.013]} />
            <mesh geometry={nodes.KeycapOG127_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.125, 0.018, 0.012]} />
            <mesh geometry={nodes.KeycapOG128_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.123, 0, 0.011]} />
            <mesh geometry={nodes.KeycapOG129_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.118, -0.018, 0.01]} />
            <mesh geometry={nodes.KeycapOG130_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.127, -0.037, 0.009]} />
            <mesh geometry={nodes.KeycapOG131_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.104, -0.037, 0.009]} />
            <mesh geometry={nodes.KeycapOG132_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.081, -0.037, 0.009]} />
            <mesh geometry={nodes.KeycapOG133_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.058, -0.037, 0.009]} />
            <mesh geometry={nodes.KeycapOG134_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.081, -0.037, 0.009]} />
            <mesh geometry={nodes.KeycapOG135_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.104, -0.037, 0.009]} />
            <mesh geometry={nodes.KeycapOG136_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.127, -0.037, 0.009]} />
            <mesh geometry={nodes.KeycapOG137_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.113, -0.019, 0.01]} />
            <mesh geometry={nodes.KeycapOG138_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.116, 0, 0.011]} />
            <mesh geometry={nodes.KeycapOG139_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.124, 0.018, 0.012]} />
            <mesh geometry={nodes.KeycapOG140_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.119, 0.037, 0.013]} />
            <mesh geometry={nodes.SPACE010_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.012, -0.037, 0.008]} />
          </group>
          <mesh geometry={nodes.Mouse_body_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
          <mesh geometry={nodes.Mouse_bottom_flat_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
          <mesh geometry={nodes.Mouse_Click_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
          <mesh geometry={nodes.Mouse_side_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
          <mesh geometry={nodes.Mouse_wheel_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.863, 2.299, -3.328]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[26.575, 20.799, -37.746]} scale={-7.162} />
    </group>
  )
}

useGLTF.preload('/kbm.glb')
