/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/Office.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Office.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[13.728, 1.775, -23.58]} rotation={[0, -1.571, 0]} scale={9.216}>
        <group position={[0.11, 0, -2.363]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bed_Single_1.geometry} material={materials.White} />
          <mesh geometry={nodes.Bed_Single_2.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Bed_Single_3.geometry} material={materials.Grey} />
          <mesh geometry={nodes.Bed_Single_4.geometry} material={materials.Red} />
          <mesh geometry={nodes.Bed_Single_5.geometry} material={materials.DarkRed} />
        </group>
      </group>
      <group position={[-17.358, 2.106, -20.592]} scale={18.807}>
        <mesh geometry={nodes.Shelf_Small2.geometry} material={materials['White.001']} position={[-0.219, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <group position={[30.348, 8.597, 0]} rotation={[0, 1.571, 0]} scale={19.337}>
        <mesh geometry={nodes.ExecutiveChair1.geometry} material={materials.LeatherExecutiveChair1} position={[-0.049, -0.111, 0.123]} rotation={[-Math.PI / 2, 0, 0]} scale={77.559} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-0.06, 0.795, -0.034]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube048_Mouse_0.geometry} material={materials.Mouse} />
          <mesh geometry={nodes.Keycap033_Mouse_0.geometry} material={materials.Mouse} position={[-0.088, -0.018, 0.01]} />
          <mesh geometry={nodes.Keycap034_Mouse_0.geometry} material={materials.Mouse} position={[-0.097, 0, 0.011]} />
          <mesh geometry={nodes.Keycap035_Mouse_0.geometry} material={materials.Mouse} position={[-0.101, 0.018, 0.012]} />
          <mesh geometry={nodes.Keycap036_Mouse_0.geometry} material={materials.Mouse} position={[-0.129, 0.037, 0.013]} />
          <mesh geometry={nodes.KeycapOG127_Mouse_0.geometry} material={materials.Mouse} position={[-0.125, 0.018, 0.012]} />
          <mesh geometry={nodes.KeycapOG128_Mouse_0.geometry} material={materials.Mouse} position={[-0.123, 0, 0.011]} />
          <mesh geometry={nodes.KeycapOG129_Mouse_0.geometry} material={materials.Mouse} position={[-0.118, -0.018, 0.01]} />
          <mesh geometry={nodes.KeycapOG130_Mouse_0.geometry} material={materials.Mouse} position={[-0.127, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG131_Mouse_0.geometry} material={materials.Mouse} position={[-0.104, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG132_Mouse_0.geometry} material={materials.Mouse} position={[-0.081, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG133_Mouse_0.geometry} material={materials.Mouse} position={[0.058, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG134_Mouse_0.geometry} material={materials.Mouse} position={[0.081, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG135_Mouse_0.geometry} material={materials.Mouse} position={[0.104, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG136_Mouse_0.geometry} material={materials.Mouse} position={[0.127, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG137_Mouse_0.geometry} material={materials.Mouse} position={[0.113, -0.019, 0.01]} />
          <mesh geometry={nodes.KeycapOG138_Mouse_0.geometry} material={materials.Mouse} position={[0.116, 0, 0.011]} />
          <mesh geometry={nodes.KeycapOG139_Mouse_0.geometry} material={materials.Mouse} position={[0.124, 0.018, 0.012]} />
          <mesh geometry={nodes.KeycapOG140_Mouse_0.geometry} material={materials.Mouse} position={[0.119, 0.037, 0.013]} />
          <mesh geometry={nodes.SPACE010_Mouse_0.geometry} material={materials.Mouse} position={[-0.012, -0.037, 0.008]} />
        </group>
        <mesh geometry={nodes.Mouse_body_low005_Mouse_0.geometry} material={materials.Mouse} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
        <mesh geometry={nodes.Mouse_bottom_flat_low005_Mouse_0.geometry} material={materials.Mouse} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
        <mesh geometry={nodes.Mouse_Click_low005_Mouse_0.geometry} material={materials.Mouse} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
        <mesh geometry={nodes.Mouse_side_low005_Mouse_0.geometry} material={materials.Mouse} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
        <mesh geometry={nodes.Mouse_wheel_low005_Mouse_0.geometry} material={materials.Mouse} position={[19.863, 2.299, -3.328]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-4.72, 0.876, 2.339]} rotation={[-1.62, -0.025, 0.1]} scale={[77.27, 87.52, 100]}>
          <mesh geometry={nodes.Cube048_Mouse_0001.geometry} material={materials['Mouse.001']} />
          <mesh geometry={nodes.Keycap033_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.088, -0.018, 0.01]} />
          <mesh geometry={nodes.Keycap034_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.097, 0, 0.011]} />
          <mesh geometry={nodes.Keycap035_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.101, 0.018, 0.012]} />
          <mesh geometry={nodes.Keycap036_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.129, 0.037, 0.013]} />
          <mesh geometry={nodes.KeycapOG127_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.125, 0.018, 0.012]} />
          <mesh geometry={nodes.KeycapOG128_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.123, 0, 0.011]} />
          <mesh geometry={nodes.KeycapOG129_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.118, -0.018, 0.01]} />
          <mesh geometry={nodes.KeycapOG130_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.127, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG131_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.104, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG132_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.081, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG133_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.058, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG134_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.081, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG135_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.104, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG136_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.127, -0.037, 0.009]} />
          <mesh geometry={nodes.KeycapOG137_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.113, -0.019, 0.01]} />
          <mesh geometry={nodes.KeycapOG138_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.116, 0, 0.011]} />
          <mesh geometry={nodes.KeycapOG139_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.124, 0.018, 0.012]} />
          <mesh geometry={nodes.KeycapOG140_Mouse_0001.geometry} material={materials['Mouse.001']} position={[0.119, 0.037, 0.013]} />
          <mesh geometry={nodes.SPACE010_Mouse_0001.geometry} material={materials['Mouse.001']} position={[-0.012, -0.037, 0.008]} />
        </group>
        <mesh geometry={nodes.Mouse_body_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
        <mesh geometry={nodes.Mouse_bottom_flat_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
        <mesh geometry={nodes.Mouse_Click_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={100} />
        <mesh geometry={nodes.Mouse_side_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.901, 2.149, 0.143]} rotation={[-Math.PI / 2, 0, -1.565]} scale={[60.47, 100, 83.03]} />
        <mesh geometry={nodes.Mouse_wheel_low005_Mouse_0001.geometry} material={materials['Mouse.001']} position={[19.863, 2.299, -3.329]} rotation={[-Math.PI / 2, 0, -1.565]} scale={[79.77, 82.7, 76.98]} />
      </group>
      <group position={[43.209, 14.648, 27.28]} rotation={[0, 1.571, 0]} scale={-38.686}>
        <mesh geometry={nodes.Computer001.geometry} material={materials['Material.003']} position={[-0.026, 0, 0]} scale={100} />
      </group>
      <mesh geometry={nodes.Cube024.geometry} material={materials['FFCC88.003']} />
      <group position={[-21.785, 0, 0]}>
        <mesh geometry={nodes['Cube_Cube001-Mesh'].geometry} material={materials['1A1A1A']} />
        <mesh geometry={nodes['Cube_Cube001-Mesh_1'].geometry} material={materials['78909C']} />
      </group>
      <group position={[-1, 0, 0]} scale={[1.64, 1, 1]}>
        <mesh geometry={nodes['Plane-Mesh'].geometry} material={materials['FFEB3B.002-2']} />
        <mesh geometry={nodes['Plane-Mesh_1'].geometry} material={materials['795548.004-2']} />
      </group>
      <mesh geometry={nodes.Desk.geometry} material={materials['Material.001']} position={[46.269, 1.706, -5.468]} rotation={[0, -Math.PI / 2, 0]} scale={2400.255} />
      <mesh geometry={nodes.Monitor.geometry} material={materials.lambert3SG} position={[50.124, 11.827, 0.597]} rotation={[0, -1.571, 0]} scale={0.041} />
      <group position={[-20.298, 6.248, 0.009]} scale={23.473}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials['mat23.001']} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials['mat16.001']} />
        <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat20} />
      </group>
      <group position={[43.646, 12.433, -9.251]} rotation={[3.095, Math.PI / 2, 0]} scale={[1147.81, 1147.811, 1147.81]}>
        <mesh geometry={nodes.Phone_1.geometry} material={materials['White.002']} />
        <mesh geometry={nodes.Phone_2.geometry} material={materials['Grey.001']} />
        <mesh geometry={nodes.Phone_3.geometry} material={materials.Black} />
      </group>
      <mesh geometry={nodes.group425587018.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={[-6.963, -6.913, -6.913]} />
      <mesh geometry={nodes.group311988427.geometry} material={materials.mat22} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group96314515.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group449779970.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group2106755496.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1753917514.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1529968652.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group252681800.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1581414308.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group295085766.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group384612072.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group150579309.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1675960081.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group287159489.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1956214489.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group196400395.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group954813675.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group706802639.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1976194690.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1152190519.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group2074153597.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1629609685.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1030983910.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group145618305.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group826580911.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group601803475.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1589752359.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group806343109.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1238060299.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group801095923.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group418912012.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group205302596.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1323238240.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1571332333.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group34220672.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1272091893.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1899843208.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group42243725.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group2146178072.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1316349499.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1754683637.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group475225180.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group77921105.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group96968687.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group268332703.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group993315105.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1740918352.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group588539140.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group729811280.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group573547017.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1180881246.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group687259746.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group45382983.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1149852049.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group790925258.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group873458270.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group616518658.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group2085389804.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1075691498.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group2091112366.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1764140354.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1238428394.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group873558583.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1486350934.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1629393722.geometry} material={materials.mat21} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group1870575723.geometry} material={materials.mat16} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.group877249531.geometry} material={materials.mat9} position={[43.741, 12.689, 2.157]} rotation={[1.094, 1.544, 2.051]} scale={-6.913} />
      <mesh geometry={nodes.Comp_Mouse.geometry} material={materials['lambert3SG.001']} position={[44.717, 12.121, 12.757]} rotation={[0, Math.PI / 2, 0]} scale={0.046} />
      <mesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials['Wolf3D_Outfit_Footwear.001']} />
      <mesh geometry={nodes.Wolf3D_Hair.geometry} material={materials['Wolf3D_Hair.001']} />
      <mesh geometry={nodes.Wolf3D_Body.geometry} material={materials['Wolf3D_Body.001']} />
      <mesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} />
      <mesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials['Wolf3D_Outfit_Top.001']} />
      <mesh geometry={nodes.Wolf3D_Body001.geometry} material={materials['Wolf3D_Body.002']} />
      <mesh geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials['Wolf3D_Outfit_Footwear.002']} />
      <mesh geometry={nodes.Wolf3D_Hair001.geometry} material={materials['Wolf3D_Hair.002']} />
      <mesh geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials['Wolf3D_Outfit_Bottom.002']} />
      <mesh geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Wolf3D_Outfit_Top.002']} />
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} />
      <mesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials['Wolf3D_Skin.001']} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <mesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.001']} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <mesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials['Wolf3D_Teeth.001']} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
      <mesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.001']} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <mesh name="Wolf3D_Head001" geometry={nodes.Wolf3D_Head001.geometry} material={materials['Wolf3D_Skin.002']} morphTargetDictionary={nodes.Wolf3D_Head001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head001.morphTargetInfluences} />
      <mesh name="Wolf3D_Teeth001" geometry={nodes.Wolf3D_Teeth001.geometry} material={materials['Wolf3D_Teeth.002']} morphTargetDictionary={nodes.Wolf3D_Teeth001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth001.morphTargetInfluences} />
      <mesh name="EyeLeft001" geometry={nodes.EyeLeft001.geometry} material={materials['Wolf3D_Eye.002']} morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences} />
      <mesh name="EyeRight001" geometry={nodes.EyeRight001.geometry} material={materials['Wolf3D_Eye.002']} morphTargetDictionary={nodes.EyeRight001.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight001.morphTargetInfluences} />
      <mesh name="EyeLeft002" geometry={nodes.EyeLeft002.geometry} material={materials['Wolf3D_Eye.002']} morphTargetDictionary={nodes.EyeLeft002.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft002.morphTargetInfluences} position={[55.053, 20.986, 26.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Computer.geometry} material={materials['Material.002']} scale={100} />
    </group>
  )
}

useGLTF.preload('/Office.glb')
