/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 CherryBlossomRawTrack.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CherryBlossomRawTrack.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.stone015.geometry} material={nodes.stone015.material} position={[-402.993, 46.992, 9.987]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/CherryBlossomRawTrack.glb')
