/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 CherryBlossomCheckPoints.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CherryBlossomCheckPoints(props) {
  const { nodes, materials } = useGLTF(
    "/~scarhatt/CherryBlossomCheckPoints.glb"
  );
  return (
    <group {...props} dispose={null} position={[5,-76,0]}>
      <group position={[-98, 0, -328]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes['New_World_(6)__-168_10_385_to_-32_130_565014'].geometry} material={materials.polished_blackstone_bricks} />
        <mesh geometry={nodes['New_World_(6)__-168_10_385_to_-32_130_565014_1'].geometry} material={materials['polished_blackstone_bricks.006']} />
        <mesh geometry={nodes['New_World_(6)__-168_10_385_to_-32_130_565014_2'].geometry} material={materials['polished_blackstone_bricks.003']} />
        <mesh geometry={nodes['New_World_(6)__-168_10_385_to_-32_130_565014_3'].geometry} material={materials['polished_blackstone_bricks.001']} />
        <mesh geometry={nodes['New_World_(6)__-168_10_385_to_-32_130_565014_4'].geometry} material={materials['polished_blackstone_bricks.002']} />
        <mesh geometry={nodes['New_World_(6)__-168_10_385_to_-32_130_565014_5'].geometry} material={materials['polished_blackstone_bricks.007']} />
      </group>
    </group>
  )
}

useGLTF.preload("/~scarhatt/CherryBlossomCheckPoints.glb");
