/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 CherryBlossomRawTrack.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function CherryBlossomRawTrack(props) {
  const { nodes, materials } = useGLTF("/CherryBlossomRawTrack.glb");

  // Set transparency and opacity to make each material invisible
  materials.stone.transparent = true;
  materials.stone.opacity = 0;

  materials.polished_blackstone_bricks.transparent = true;
  materials.polished_blackstone_bricks.opacity = 0;

  materials["polished_blackstone_bricks.006"].transparent = true;
  materials["polished_blackstone_bricks.006"].opacity = 0;

  materials["polished_blackstone_bricks.003"].transparent = true;
  materials["polished_blackstone_bricks.003"].opacity = 0;

  materials["polished_blackstone_bricks.001"].transparent = true;
  materials["polished_blackstone_bricks.001"].opacity = 0;

  materials["polished_blackstone_bricks.002"].transparent = true;
  materials["polished_blackstone_bricks.002"].opacity = 0;

  materials["polished_blackstone_bricks.007"].transparent = true;
  materials["polished_blackstone_bricks.007"].opacity = 0;

  return (
    <group {...props} dispose={null} position={[5, -76, 0]}>
      <RigidBody type="fixed" colliders="trimesh">
        <group position={[-98, 0, -328]} rotation={[Math.PI / 2, 0, Math.PI]}>
          <mesh
            geometry={
              nodes["New_World_(6)__-168_10_385_to_-32_130_565003"].geometry
            }
            material={materials.stone}
          />
          <mesh
            geometry={
              nodes["New_World_(6)__-168_10_385_to_-32_130_565003_1"].geometry
            }
            material={materials.polished_blackstone_bricks}
          />
          <mesh
            geometry={
              nodes["New_World_(6)__-168_10_385_to_-32_130_565003_2"].geometry
            }
            material={materials["polished_blackstone_bricks.006"]}
          />
          <mesh
            geometry={
              nodes["New_World_(6)__-168_10_385_to_-32_130_565003_3"].geometry
            }
            material={materials["polished_blackstone_bricks.003"]}
          />
          <mesh
            geometry={
              nodes["New_World_(6)__-168_10_385_to_-32_130_565003_4"].geometry
            }
            material={materials["polished_blackstone_bricks.001"]}
          />
          <mesh
            geometry={
              nodes["New_World_(6)__-168_10_385_to_-32_130_565003_5"].geometry
            }
            material={materials["polished_blackstone_bricks.002"]}
          />
          <mesh
            geometry={
              nodes["New_World_(6)__-168_10_385_to_-32_130_565003_6"].geometry
            }
            material={materials["polished_blackstone_bricks.007"]}
          />
        </group>
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/CherryBlossomRawTrack.glb");
