/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 WholeMap.glb 
*/

import React, {useEffect} from "react";
import { useGLTF } from "@react-three/drei";

export function Map(props) {
  
  const { nodes, materials } = useGLTF("/WholeMap.glb");
  useEffect(() => {
    // Reset emissive materials
    Object.values(materials).forEach((material) => {
      if (material.emissive) material.emissive.set(0, 0, 0);
      material.emissiveIntensity = 1;
    });
  }, [materials, nodes]);
  return (
    <group {...props} dispose={null} position={[49, -66,-17]}>

      <group position={[2, 47, -189]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003"].geometry
          }
          material={materials["stone.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_1"].geometry
          }
          material={materials["granite.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_2"].geometry
          }
          material={materials["diorite.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_3"].geometry
          }
          material={materials["andesite.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_4"].geometry
          }
          material={materials["polished_blackstone_bricks.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_5"].geometry
          }
          material={materials["grass_block_top.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_6"].geometry
          }
          material={materials["dirt.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_7"].geometry
          }
          material={materials["grass_block_side.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_8"].geometry
          }
          material={materials["cherry_sapling.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_9"].geometry
          }
          material={materials["water_still.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_10"].geometry
          }
          material={materials["sand.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_11"].geometry
          }
          material={materials["gravel.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_12"].geometry
          }
          material={materials["iron_ore.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_13"].geometry
          }
          material={materials["coal_ore.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_14"].geometry
          }
          material={materials["grass.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_15"].geometry
          }
          material={materials["clay.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_16"].geometry
          }
          material={materials["tall_grass_bottom.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_17"].geometry
          }
          material={materials["tall_grass_top.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_18"].geometry
          }
          material={materials["magma.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_19"].geometry
          }
          material={materials["white_concrete.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_20"].geometry
          }
          material={materials["black_concrete.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_21"].geometry
          }
          material={materials["bee_nest_bottom.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_22"].geometry
          }
          material={materials["bee_nest_front_honey.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_23"].geometry
          }
          material={materials["bee_nest_side.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_24"].geometry
          }
          material={materials["bee_nest_top.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_25"].geometry
          }
          material={materials["copper_ore.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_26"].geometry
          }
          material={materials["glow_lichen.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_27"].geometry
          }
          material={materials["cherry_log.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_28"].geometry
          }
          material={materials["cherry_log_top.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_29"].geometry
          }
          material={materials["cherry_leaves.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_30"].geometry
          }
          material={materials["pink_petals.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269003_31"].geometry
          }
          material={materials["pink_petals_stem.004"]}
        />
      </group>
      <group
        position={[-402.993, 46.992, 9.987]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005"].geometry
          }
          material={materials["stone.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_1"].geometry
          }
          material={materials["granite.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_2"].geometry
          }
          material={materials["diorite.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_3"].geometry
          }
          material={materials["andesite.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_4"].geometry
          }
          material={materials["polished_blackstone_bricks.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_5"].geometry
          }
          material={materials["grass_block_top.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_6"].geometry
          }
          material={materials["dirt.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_7"].geometry
          }
          material={materials["grass_block_side.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_8"].geometry
          }
          material={materials["cherry_sapling.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_9"].geometry
          }
          material={materials["water_still.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_10"].geometry
          }
          material={materials["sand.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_11"].geometry
          }
          material={materials["gravel.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_12"].geometry
          }
          material={materials["iron_ore.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_13"].geometry
          }
          material={materials["coal_ore.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_14"].geometry
          }
          material={materials["grass.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_15"].geometry
          }
          material={materials["clay.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_16"].geometry
          }
          material={materials["tall_grass_bottom.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_17"].geometry
          }
          material={materials["tall_grass_top.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_18"].geometry
          }
          material={materials["magma.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_19"].geometry
          }
          material={materials["white_concrete.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_20"].geometry
          }
          material={materials["black_concrete.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_21"].geometry
          }
          material={materials["bee_nest_bottom.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_22"].geometry
          }
          material={materials["bee_nest_front_honey.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_23"].geometry
          }
          material={materials["bee_nest_side.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_24"].geometry
          }
          material={materials["bee_nest_top.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_25"].geometry
          }
          material={materials["copper_ore.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_26"].geometry
          }
          material={materials["glow_lichen.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_27"].geometry
          }
          material={materials["cherry_log.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_28"].geometry
          }
          material={materials["cherry_log_top.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_29"].geometry
          }
          material={materials["cherry_leaves.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_30"].geometry
          }
          material={materials["pink_petals.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-909_53_162_to_-777_319_269005_31"].geometry
          }
          material={materials["pink_petals_stem.004"]}
        />
      </group>
      <group
        position={[-190.996, 31, -218]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003"].geometry
          }
          material={materials["stone.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_1"].geometry
          }
          material={materials["granite.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_2"].geometry
          }
          material={materials["diorite.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_3"].geometry
          }
          material={materials["andesite.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_4"].geometry
          }
          material={materials["polished_blackstone_bricks.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_5"].geometry
          }
          material={materials["grass_block_top.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_6"].geometry
          }
          material={materials["dirt.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_7"].geometry
          }
          material={materials["grass_block_side.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_8"].geometry
          }
          material={materials["cherry_sapling.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_9"].geometry
          }
          material={materials["water_still.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_10"].geometry
          }
          material={materials["water_flow.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_11"].geometry
          }
          material={materials["sand.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_12"].geometry
          }
          material={materials["gravel.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_13"].geometry
          }
          material={materials["iron_ore.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_14"].geometry
          }
          material={materials["coal_ore.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_15"].geometry
          }
          material={materials["lapis_ore.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_16"].geometry
          }
          material={materials["sandstone_top.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_17"].geometry
          }
          material={materials["sandstone.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_18"].geometry
          }
          material={materials["sandstone_bottom.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_19"].geometry
          }
          material={materials["grass.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_20"].geometry
          }
          material={materials["clay.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_21"].geometry
          }
          material={materials["tall_grass_bottom.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_22"].geometry
          }
          material={materials["tall_grass_top.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_23"].geometry
          }
          material={materials["magma.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_24"].geometry
          }
          material={materials["white_concrete.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_25"].geometry
          }
          material={materials["black_concrete.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_26"].geometry
          }
          material={materials["bee_nest_bottom.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_27"].geometry
          }
          material={materials["bee_nest_front.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_28"].geometry
          }
          material={materials["bee_nest_front_honey.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_29"].geometry
          }
          material={materials["bee_nest_side.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_30"].geometry
          }
          material={materials["bee_nest_top.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_31"].geometry
          }
          material={materials["copper_ore.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_32"].geometry
          }
          material={materials["glow_lichen.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_33"].geometry
          }
          material={materials["cherry_log.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_34"].geometry
          }
          material={materials["cherry_log_top.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_35"].geometry
          }
          material={materials["cherry_leaves.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_36"].geometry
          }
          material={materials["pink_petals.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531003_37"].geometry
          }
          material={materials["pink_petals_stem.005"]}
        />
      </group>
      <group
        position={[-209.997, 30.992, 38.987]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004"].geometry
          }
          material={materials["stone.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_1"].geometry
          }
          material={materials["granite.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_2"].geometry
          }
          material={materials["diorite.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_3"].geometry
          }
          material={materials["andesite.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_4"].geometry
          }
          material={materials["polished_blackstone_bricks.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_5"].geometry
          }
          material={materials["grass_block_top.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_6"].geometry
          }
          material={materials["dirt.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_7"].geometry
          }
          material={materials["grass_block_side.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_8"].geometry
          }
          material={materials["cherry_sapling.004"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_9"].geometry
          }
          material={materials["water_still.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_10"].geometry
          }
          material={materials["water_flow.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_11"].geometry
          }
          material={materials["sand.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_12"].geometry
          }
          material={materials["gravel.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_13"].geometry
          }
          material={materials["iron_ore.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_14"].geometry
          }
          material={materials["coal_ore.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_15"].geometry
          }
          material={materials["lapis_ore.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_16"].geometry
          }
          material={materials["sandstone_top.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_17"].geometry
          }
          material={materials["sandstone.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_18"].geometry
          }
          material={materials["sandstone_bottom.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_19"].geometry
          }
          material={materials["grass.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_20"].geometry
          }
          material={materials["clay.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_21"].geometry
          }
          material={materials["tall_grass_bottom.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_22"].geometry
          }
          material={materials["tall_grass_top.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_23"].geometry
          }
          material={materials["magma.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_24"].geometry
          }
          material={materials["white_concrete.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_25"].geometry
          }
          material={materials["black_concrete.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_26"].geometry
          }
          material={materials["bee_nest_bottom.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_27"].geometry
          }
          material={materials["bee_nest_front.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_28"].geometry
          }
          material={materials["bee_nest_front_honey.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_29"].geometry
          }
          material={materials["bee_nest_side.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_30"].geometry
          }
          material={materials["bee_nest_top.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_31"].geometry
          }
          material={materials["copper_ore.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_32"].geometry
          }
          material={materials["glow_lichen.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_33"].geometry
          }
          material={materials["cherry_log.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_34"].geometry
          }
          material={materials["cherry_log_top.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_35"].geometry
          }
          material={materials["cherry_leaves.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_36"].geometry
          }
          material={materials["pink_petals.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-524_34_315_to_-296_319_531004_37"].geometry
          }
          material={materials["pink_petals_stem.005"]}
        />
      </group>
      {/* <group position={[-401, 0, -179]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003"].geometry
          }
          material={materials["stone.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_1"].geometry
          }
          material={materials["granite.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_2"].geometry
          }
          material={materials["diorite.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_3"].geometry
          }
          material={materials["andesite.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_4"].geometry
          }
          material={materials["polished_blackstone_bricks.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_5"].geometry
          }
          material={materials["grass_block_top.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_6"].geometry
          }
          material={materials["dirt.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_7"].geometry
          }
          material={materials["grass_block_side.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_8"].geometry
          }
          material={materials["cobblestone.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_9"].geometry
          }
          material={materials["water_still.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_10"].geometry
          }
          material={materials["water_flow.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_11"].geometry
          }
          material={materials["sand.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_12"].geometry
          }
          material={materials["gravel.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_13"].geometry
          }
          material={materials["iron_ore.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_14"].geometry
          }
          material={materials["coal_ore.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_15"].geometry
          }
          material={materials["oak_log.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_16"].geometry
          }
          material={materials["oak_log_top.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_17"].geometry
          }
          material={materials["grass.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_18"].geometry
          }
          material={materials["clay.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_19"].geometry
          }
          material={materials["oak_planks.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_20"].geometry
          }
          material={materials["emerald_ore.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_21"].geometry
          }
          material={materials["tall_grass_bottom.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_22"].geometry
          }
          material={materials["tall_grass_top.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_23"].geometry
          }
          material={materials["white_concrete.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_24"].geometry
          }
          material={materials["black_concrete.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_25"].geometry
          }
          material={materials["lantern.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_26"].geometry
          }
          material={materials["bee_nest_bottom.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_27"].geometry
          }
          material={materials["bee_nest_front_honey.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_28"].geometry
          }
          material={materials["bee_nest_side.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_29"].geometry
          }
          material={materials["bee_nest_top.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_30"].geometry
          }
          material={materials["copper_ore.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_31"].geometry
          }
          material={materials["glow_lichen.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_32"].geometry
          }
          material={materials["cherry_log.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_33"].geometry
          }
          material={materials["cherry_log_top.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_34"].geometry
          }
          material={materials["cherry_leaves.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_35"].geometry
          }
          material={materials["pink_petals.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582003_36"].geometry
          }
          material={materials["pink_petals_stem.008"]}
        />
      </group> */}
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow
          geometry={nodes["New_World_(6)__-163_20_386_to_-6_319_582"].geometry}
          material={materials["stone.008"]}
        />
        <mesh castShadow receiveShadow  
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_1"].geometry
          }
          material={materials["granite.008"]}
        />
        <mesh castShadow receiveShadow  
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_2"].geometry
          }
          material={materials["diorite.008"]}
        />
        <mesh castShadow receiveShadow 
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_3"].geometry
          }
          material={materials["andesite.008"]}
        />
        <mesh castShadow receiveShadow  
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_4"].geometry
          }
          material={materials["polished_blackstone_bricks.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_5"].geometry
          }
          material={materials["grass_block_top.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_6"].geometry
          }
          material={materials["dirt.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_7"].geometry
          }
          material={materials["grass_block_side.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_8"].geometry
          }
          material={materials["cobblestone.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_9"].geometry
          }
          material={materials["water_still.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_10"].geometry
          }
          material={materials["water_flow.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_11"].geometry
          }
          material={materials["sand.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_12"].geometry
          }
          material={materials["gravel.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_13"].geometry
          }
          material={materials["iron_ore.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_14"].geometry
          }
          material={materials["coal_ore.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_15"].geometry
          }
          material={materials["oak_log.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_16"].geometry
          }
          material={materials["oak_log_top.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_17"].geometry
          }
          material={materials["grass.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_18"].geometry
          }
          material={materials["clay.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_19"].geometry
          }
          material={materials["oak_planks.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_20"].geometry
          }
          material={materials["emerald_ore.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_21"].geometry
          }
          material={materials["tall_grass_bottom.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_22"].geometry
          }
          material={materials["tall_grass_top.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_23"].geometry
          }
          material={materials["white_concrete.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_24"].geometry
          }
          material={materials["black_concrete.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_25"].geometry
          }
          material={materials["lantern.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_26"].geometry
          }
          material={materials["bee_nest_bottom.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_27"].geometry
          }
          material={materials["bee_nest_front_honey.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_28"].geometry
          }
          material={materials["bee_nest_side.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_29"].geometry
          }
          material={materials["bee_nest_top.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_30"].geometry
          }
          material={materials["copper_ore.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_31"].geometry
          }
          material={materials["glow_lichen.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_32"].geometry
          }
          material={materials["cherry_log.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_33"].geometry
          }
          material={materials["cherry_log_top.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_34"].geometry
          }
          material={materials["cherry_leaves.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_35"].geometry
          }
          material={materials["pink_petals.008"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-163_20_386_to_-6_319_582_36"].geometry
          }
          material={materials["pink_petals_stem.008"]}
        />
      </group>
      <group position={[-6, 58, -116]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277"].geometry
          }
          material={materials["stone.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_1"].geometry
          }
          material={materials["granite.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_2"].geometry
          }
          material={materials["andesite.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_3"].geometry
          }
          material={materials["polished_blackstone_bricks.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_4"].geometry
          }
          material={materials["grass_block_top.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_5"].geometry
          }
          material={materials["dirt.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_6"].geometry
          }
          material={materials["grass_block_side.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_7"].geometry
          }
          material={materials["gravel.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_8"].geometry
          }
          material={materials["iron_ore.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_9"].geometry
          }
          material={materials["coal_ore.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_10"].geometry
          }
          material={materials["grass.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_11"].geometry
          }
          material={materials["emerald_ore.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_12"].geometry
          }
          material={materials["tall_grass_bottom.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_13"].geometry
          }
          material={materials["tall_grass_top.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_14"].geometry
          }
          material={materials["white_concrete.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_15"].geometry
          }
          material={materials["black_concrete.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_16"].geometry
          }
          material={materials["copper_ore.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_17"].geometry
          }
          material={materials["glow_lichen.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_18"].geometry
          }
          material={materials["cherry_log.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_19"].geometry
          }
          material={materials["cherry_log_top.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_20"].geometry
          }
          material={materials["cherry_leaves.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_21"].geometry
          }
          material={materials["pink_petals.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277_22"].geometry
          }
          material={materials["pink_petals_stem.009"]}
        />
      </group>
      <group
        position={[-394.993, 57.992, -63.013]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005"].geometry
          }
          material={materials["stone.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_1"].geometry
          }
          material={materials["granite.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_2"].geometry
          }
          material={materials["andesite.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_3"].geometry
          }
          material={materials["polished_blackstone_bricks.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_4"].geometry
          }
          material={materials["grass_block_top.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_5"].geometry
          }
          material={materials["dirt.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_6"].geometry
          }
          material={materials["grass_block_side.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_7"].geometry
          }
          material={materials["gravel.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_8"].geometry
          }
          material={materials["iron_ore.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_9"].geometry
          }
          material={materials["coal_ore.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_10"].geometry
          }
          material={materials["grass.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_11"].geometry
          }
          material={materials["emerald_ore.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_12"].geometry
          }
          material={materials["tall_grass_bottom.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_13"].geometry
          }
          material={materials["tall_grass_top.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_14"].geometry
          }
          material={materials["white_concrete.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_15"].geometry
          }
          material={materials["black_concrete.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_16"].geometry
          }
          material={materials["copper_ore.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_17"].geometry
          }
          material={materials["glow_lichen.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_18"].geometry
          }
          material={materials["cherry_log.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_19"].geometry
          }
          material={materials["cherry_log_top.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_20"].geometry
          }
          material={materials["cherry_leaves.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_21"].geometry
          }
          material={materials["pink_petals.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-537_104_237_to_-500_153_277005_22"].geometry
          }
          material={materials["pink_petals_stem.009"]}
        />
      </group>
      <group
        position={[-64, 45, -181]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh castShadow receiveShadow
          geometry={nodes["New_World_(6)__-560_30_425_to_-520_79_492"].geometry}
          material={materials["stone.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_1"].geometry
          }
          material={materials["granite.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_2"].geometry
          }
          material={materials["diorite.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_3"].geometry
          }
          material={materials["andesite.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_4"].geometry
          }
          material={materials["polished_blackstone_bricks.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_5"].geometry
          }
          material={materials["grass_block_top.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_6"].geometry
          }
          material={materials["dirt.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_7"].geometry
          }
          material={materials["grass_block_side.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_8"].geometry
          }
          material={materials["water_still.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_9"].geometry
          }
          material={materials["gravel.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_10"].geometry
          }
          material={materials["iron_ore.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_11"].geometry
          }
          material={materials["coal_ore.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_12"].geometry
          }
          material={materials["grass.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_13"].geometry
          }
          material={materials["tall_grass_bottom.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_14"].geometry
          }
          material={materials["tall_grass_top.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_15"].geometry
          }
          material={materials["white_concrete.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_16"].geometry
          }
          material={materials["black_concrete.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_17"].geometry
          }
          material={materials["copper_ore.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_18"].geometry
          }
          material={materials["glow_lichen.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_19"].geometry
          }
          material={materials["cherry_log.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_20"].geometry
          }
          material={materials["cherry_log_top.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_21"].geometry
          }
          material={materials["cherry_leaves.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_22"].geometry
          }
          material={materials["pink_petals.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492_23"].geometry
          }
          material={materials["pink_petals_stem.010"]}
        />
      </group>
      <group
        position={[-336.993, 44.992, 1.987]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006"].geometry
          }
          material={materials["stone.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_1"].geometry
          }
          material={materials["granite.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_2"].geometry
          }
          material={materials["diorite.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_3"].geometry
          }
          material={materials["andesite.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_4"].geometry
          }
          material={materials["polished_blackstone_bricks.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_5"].geometry
          }
          material={materials["grass_block_top.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_6"].geometry
          }
          material={materials["dirt.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_7"].geometry
          }
          material={materials["grass_block_side.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_8"].geometry
          }
          material={materials["water_still.009"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_9"].geometry
          }
          material={materials["gravel.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_10"].geometry
          }
          material={materials["iron_ore.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_11"].geometry
          }
          material={materials["coal_ore.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_12"].geometry
          }
          material={materials["grass.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_13"].geometry
          }
          material={materials["tall_grass_bottom.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_14"].geometry
          }
          material={materials["tall_grass_top.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_15"].geometry
          }
          material={materials["white_concrete.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_16"].geometry
          }
          material={materials["black_concrete.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_17"].geometry
          }
          material={materials["copper_ore.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_18"].geometry
          }
          material={materials["glow_lichen.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_19"].geometry
          }
          material={materials["cherry_log.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_20"].geometry
          }
          material={materials["cherry_log_top.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_21"].geometry
          }
          material={materials["cherry_leaves.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_22"].geometry
          }
          material={materials["pink_petals.010"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-560_30_425_to_-520_79_492006_23"].geometry
          }
          material={materials["pink_petals_stem.010"]}
        />
      </group>
      <group position={[-305.002, 26, -229]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow
          geometry={nodes["New_World_(6)__-451_67_11_to_-412_173_36"].geometry}
          material={materials["stone.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_1"].geometry
          }
          material={materials["andesite.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_2"].geometry
          }
          material={materials["polished_blackstone_bricks.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_3"].geometry
          }
          material={materials["grass_block_top.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_4"].geometry
          }
          material={materials["dirt.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_5"].geometry
          }
          material={materials["grass_block_side.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_6"].geometry
          }
          material={materials["iron_ore.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_7"].geometry
          }
          material={materials["coal_ore.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_8"].geometry
          }
          material={materials["grass.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_9"].geometry
          }
          material={materials["emerald_ore.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_10"].geometry
          }
          material={materials["white_concrete.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_11"].geometry
          }
          material={materials["black_concrete.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_12"].geometry
          }
          material={materials["cherry_log.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_13"].geometry
          }
          material={materials["cherry_log_top.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_14"].geometry
          }
          material={materials["cherry_leaves.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_15"].geometry
          }
          material={materials["pink_petals.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36_16"].geometry
          }
          material={materials["pink_petals_stem.011"]}
        />
      </group>
      
      <group
        position={[-95.992, 25.992, 49.987]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002"].geometry
          }
          material={materials["stone.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_1"].geometry
          }
          material={materials["andesite.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_2"].geometry
          }
          material={materials["polished_blackstone_bricks.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_3"].geometry
          }
          material={materials["grass_block_top.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_4"].geometry
          }
          material={materials["dirt.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_5"].geometry
          }
          material={materials["grass_block_side.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_6"].geometry
          }
          material={materials["iron_ore.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_7"].geometry
          }
          material={materials["coal_ore.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_8"].geometry
          }
          material={materials["grass.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_9"].geometry
          }
          material={materials["emerald_ore.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_10"].geometry
          }
          material={materials["white_concrete.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_11"].geometry
          }
          material={materials["black_concrete.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_12"].geometry
          }
          material={materials["cherry_log.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_13"].geometry
          }
          material={materials["cherry_log_top.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_14"].geometry
          }
          material={materials["cherry_leaves.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_15"].geometry
          }
          material={materials["pink_petals.011"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(6)__-451_67_11_to_-412_173_36002_16"].geometry
          }
          material={materials["pink_petals_stem.011"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/WholeMap.glb");
