/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 NetherRawTrack.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody, Physics } from "@react-three/rapier";
import { getBaseUrl } from "../../../utils/getURL";

export function NetherRawTrackWalls(props) {
  const { nodes, materials } = useGLTF(`/~scarhatt/NetherRawTrack.glb`);
  materials[nodes.blackstone_top014.material.name].transparent = true;
  materials[nodes.blackstone_top014.material.name].opacity = 0;
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh" position={[15, -140, -17]}>
        <mesh
          geometry={nodes.blackstone_top014.geometry}
          material={nodes.blackstone_top014.material}
          position={[255, 0, 0]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload(`/~scarhatt/NetherRawTrack.glb`);
