/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 NetherCheckPoints.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function NetherCheckPoints(props) {
  const { nodes, materials } = useGLTF("/NetherCheckPoints.glb");
  return (
    <group {...props} dispose={null} position={[17, -140, 0]}>
      <group position={[255, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261014"].geometry
          }
          material={materials["polished_blackstone_bricks.005"]}
        />
        <mesh
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261014_1"]
              .geometry
          }
          material={materials.polished_blackstone_bricks}
        />
        <mesh
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261014_2"]
              .geometry
          }
          material={materials["polished_blackstone_bricks.002"]}
        />
        <mesh
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261014_3"]
              .geometry
          }
          material={materials["polished_blackstone_bricks.003"]}
        />
        <mesh
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261014_4"]
              .geometry
          }
          material={materials["polished_blackstone_bricks.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/NetherCheckPoints.glb");
