/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 CherryBlossomHome.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CherryBlossomHome(props) {
  const { nodes, materials } = useGLTF('/CherryBlossomHome.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-10, 28, 180]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002'].geometry} material={materials['stone.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_1'].geometry} material={materials['diorite.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_2'].geometry} material={materials['andesite.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_3'].geometry} material={materials['polished_blackstone_bricks.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_4'].geometry} material={materials['grass_block_top.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_5'].geometry} material={materials['dirt.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_6'].geometry} material={materials['grass_block_side.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_7'].geometry} material={materials['cherry_sapling.001']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_8'].geometry} material={materials['water_still.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_9'].geometry} material={materials['sand.002']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_10'].geometry} material={materials['gravel.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_11'].geometry} material={materials['iron_ore.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_12'].geometry} material={materials['coal_ore.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_13'].geometry} material={materials['grass.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_14'].geometry} material={materials['clay.002']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_15'].geometry} material={materials['tall_grass_bottom.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_16'].geometry} material={materials['tall_grass_top.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_17'].geometry} material={materials['white_concrete.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_18'].geometry} material={materials['black_concrete.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_19'].geometry} material={materials['bee_nest_bottom.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_20'].geometry} material={materials['bee_nest_front_honey.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_21'].geometry} material={materials['bee_nest_side.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_22'].geometry} material={materials['bee_nest_top.002']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_23'].geometry} material={materials['copper_ore.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_24'].geometry} material={materials['glow_lichen.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_25'].geometry} material={materials['cherry_log.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_26'].geometry} material={materials['cherry_log_top.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_27'].geometry} material={materials['cherry_leaves.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_28'].geometry} material={materials['pink_petals.003']} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-905_54_163_to_-821_130_234002_29'].geometry} material={materials['pink_petals_stem.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/CherryBlossomHome.glb')
