/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 EndHome.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EndHome(props) {
  const { nodes, materials } = useGLTF('/EndHome.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[16,6, 130]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003'].geometry} material={materials.polished_blackstone_bricks} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_1'].geometry} material={materials.piston_side} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_2'].geometry} material={materials.MWO_chest_top} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_3'].geometry} material={materials.MWO_chest_side} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_4'].geometry} material={materials.MWO_chest_front} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_5'].geometry} material={materials.MWO_chest_latch} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_6'].geometry} material={materials.ladder} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_7'].geometry} material={materials.magenta_stained_glass} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_8'].geometry} material={materials.end_stone} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_9'].geometry} material={materials.MWO_ender_chest_latch} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_10'].geometry} material={materials.MWO_ender_chest_top} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_11'].geometry} material={materials.MWO_ender_chest_side} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_12'].geometry} material={materials.MWO_ender_chest_front} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_13'].geometry} material={materials.end_rod} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_14'].geometry} material={materials.chorus_plant} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_15'].geometry} material={materials.chorus_flower} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_16'].geometry} material={materials.chorus_flower_dead} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_17'].geometry} material={materials.purpur_block} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_18'].geometry} material={materials.purpur_pillar} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_19'].geometry} material={materials.purpur_pillar_top} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_20'].geometry} material={materials.end_stone_bricks} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_21'].geometry} material={materials.white_concrete} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_22'].geometry} material={materials.black_concrete} />
        <mesh castShadow receiveShadow geometry={nodes['New_World_(6)__-328_20_98902_to_-143_319_99077003_23'].geometry} material={materials.magenta_concrete} />
      </group>
    </group>
  )
}

useGLTF.preload('/EndHome.glb')
