/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Hummer.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function HomeHummer(props) {
  const { nodes, materials } = useGLTF("/Hummer.glb");
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.hummer_h1_3.geometry}
        material={materials.Element}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.127}
      />
    </group>
  );
}

useGLTF.preload("/Hummer.glb");
