/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Car.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HomeCar(props) {
  const { nodes, materials } = useGLTF('/Car.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.039, -0.035, -0.026]} rotation={[-Math.PI / 2, 0, 0]} scale={0.461}>
        <mesh geometry={nodes.Punto_GT_0.geometry} material={materials.gt_black} />
        <mesh geometry={nodes.Punto_GT_1.geometry} material={materials.gt_license} />
        <mesh geometry={nodes.Punto_GT_2.geometry} material={materials.gt_tire} />
        <mesh geometry={nodes.Punto_GT_3.geometry} material={materials.gt_rim} />
        <mesh geometry={nodes.Punto_GT_4.geometry} material={materials.gt_windows} />
        <mesh geometry={nodes.Punto_GT_5.geometry} material={materials['Hemi.001']} />
        <mesh geometry={nodes.Punto_GT_6.geometry} material={materials.gt_body} />
        <mesh geometry={nodes.Punto_GT_7.geometry} material={materials.gt_details} />
      </group>
     
    </group>
  )
}

useGLTF.preload('/Car.glb')
