/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 NetherHome.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function NetherHome(props) {
  const { nodes, materials } = useGLTF('/NetherHome.glb')
  return (
    <group {...props} dispose={null} rotation={[0, Math.PI / 2, 0]}>
      <group position={[-199, -95,-15]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003"].geometry
          }
          material={materials["polished_blackstone_bricks.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_1"]
              .geometry
          }
          material={materials["nether_gold_ore.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_2"]
              .geometry
          }
          material={materials["netherrack.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_3"]
              .geometry
          }
          material={materials["crimson_nylium.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_4"]
              .geometry
          }
          material={materials["crimson_nylium_side.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_5"]
              .geometry
          }
          material={materials["warped_nylium.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_6"]
              .geometry
          }
          material={materials["warped_nylium_side.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_7"]
              .geometry
          }
          material={materials["lava_still.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_8"]
              .geometry
          }
          material={materials["lava_flow.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_9"]
              .geometry
          }
          material={materials["nether_sprouts.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_10"]
              .geometry
          }
          material={materials["crimson_roots.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_11"]
              .geometry
          }
          material={materials["warped_roots.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_12"]
              .geometry
          }
          material={materials["crimson_fungus.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_13"]
              .geometry
          }
          material={materials["warped_fungus.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_14"]
              .geometry
          }
          material={materials["fire_0.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_15"]
              .geometry
          }
          material={materials["glowstone.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_16"]
              .geometry
          }
          material={materials["shroomlight.003"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_17"]
              .geometry
          }
          material={materials["nether_quartz_ore.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_18"]
              .geometry
          }
          material={materials["crimson_stem_top.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_19"]
              .geometry
          }
          material={materials["crimson_stem.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_20"]
              .geometry
          }
          material={materials["warped_stem_top.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_21"]
              .geometry
          }
          material={materials["warped_stem.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_22"]
              .geometry
          }
          material={materials["nether_wart_block.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_23"]
              .geometry
          }
          material={materials["warped_wart_block.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_24"]
              .geometry
          }
          material={materials["white_concrete.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_25"]
              .geometry
          }
          material={materials["black_concrete.005"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_26"]
              .geometry
          }
          material={materials["weeping_vines.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_27"]
              .geometry
          }
          material={materials["weeping_vines_plant.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_28"]
              .geometry
          }
          material={materials["twisting_vines.002"]}
        />
        <mesh castShadow receiveShadow
          geometry={
            nodes["New_World_(8)__-386_-64_-1394_to_-287_126_-1261003_29"]
              .geometry
          }
          material={materials["twisting_vines_plant.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/NetherHome.glb')
