/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 UnderWaterWhole.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/UnderWaterWhole.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[152, -42, 56]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057'].geometry} material={materials.tube_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_1'].geometry} material={materials.suspicious_sand_0} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_2'].geometry} material={materials['stone.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_3'].geometry} material={materials['granite.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_4'].geometry} material={materials.polished_granite} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_5'].geometry} material={materials['diorite.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_6'].geometry} material={materials['andesite.002']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_7'].geometry} material={materials['polished_blackstone_bricks.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_8'].geometry} material={materials['dirt.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_9'].geometry} material={materials.water_still} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_10'].geometry} material={materials.water_flow} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_11'].geometry} material={materials['sand.001']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_12'].geometry} material={materials['gravel.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_13'].geometry} material={materials['iron_ore.002']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_14'].geometry} material={materials['coal_ore.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_15'].geometry} material={materials['oak_log.003']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_16'].geometry} material={materials.lapis_ore} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_17'].geometry} material={materials.sandstone_top} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_18'].geometry} material={materials.sandstone} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_19'].geometry} material={materials.sandstone_bottom} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_20'].geometry} material={materials.cut_sandstone} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_21'].geometry} material={materials.MWO_chest_top} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_22'].geometry} material={materials.MWO_chest_side} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_23'].geometry} material={materials.MWO_chest_front} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_24'].geometry} material={materials.MWO_chest_latch} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_25'].geometry} material={materials.light_blue_terracotta} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_26'].geometry} material={materials.dark_prismarine} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_27'].geometry} material={materials.sea_lantern} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_28'].geometry} material={materials['white_concrete.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_29'].geometry} material={materials['black_concrete.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_30'].geometry} material={materials.tall_seagrass_bottom} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_31'].geometry} material={materials.tall_seagrass_top} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_32'].geometry} material={materials.tube_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_33'].geometry} material={materials.brain_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_34'].geometry} material={materials.bubble_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_35'].geometry} material={materials.fire_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_36'].geometry} material={materials.horn_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_37'].geometry} material={materials.tube_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_38'].geometry} material={materials.brain_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_39'].geometry} material={materials.bubble_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_40'].geometry} material={materials.fire_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_41'].geometry} material={materials.horn_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_42'].geometry} material={materials.brain_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_43'].geometry} material={materials.bubble_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_44'].geometry} material={materials.fire_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_45'].geometry} material={materials.horn_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_46'].geometry} material={materials.sea_pickle} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_47'].geometry} material={materials['lantern.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_48'].geometry} material={materials.blackstone_top} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_49'].geometry} material={materials.blackstone} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_50'].geometry} material={materials['copper_ore.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_51'].geometry} material={materials.raw_copper_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_52'].geometry} material={materials['glow_lichen.001']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_53'].geometry} material={materials['andesite.005']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_54'].geometry} material={materials['black_concrete.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_55'].geometry} material={materials['coal_ore.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_56'].geometry} material={materials['copper_ore.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_57'].geometry} material={materials['deepslate_top.005']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_58'].geometry} material={materials['deepslate.005']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_59'].geometry} material={materials['diorite.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_60'].geometry} material={materials['dirt.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_61'].geometry} material={materials['granite.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_62'].geometry} material={materials['gravel.008']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_63'].geometry} material={materials['iron_ore.005']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_64'].geometry} material={materials['lantern.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_65'].geometry} material={materials['oak_log.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_66'].geometry} material={materials['oak_log_top.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_67'].geometry} material={materials['polished_blackstone_bricks.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_68'].geometry} material={materials['lava_still.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_69'].geometry} material={materials['stone.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864057_70'].geometry} material={materials['white_concrete.007']} />
      </group>
      <group position={[-8, -43, 143]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045'].geometry} material={materials.tube_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_1'].geometry} material={materials.suspicious_sand_0} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_2'].geometry} material={materials['stone.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_3'].geometry} material={materials['granite.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_4'].geometry} material={materials.polished_granite} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_5'].geometry} material={materials['diorite.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_6'].geometry} material={materials['andesite.002']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_7'].geometry} material={materials['polished_blackstone_bricks.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_8'].geometry} material={materials['dirt.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_9'].geometry} material={materials.water_still} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_10'].geometry} material={materials.water_flow} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_11'].geometry} material={materials['sand.001']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_12'].geometry} material={materials['gravel.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_13'].geometry} material={materials['iron_ore.002']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_14'].geometry} material={materials['coal_ore.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_15'].geometry} material={materials['oak_log.003']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_16'].geometry} material={materials.lapis_ore} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_17'].geometry} material={materials.sandstone_top} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_18'].geometry} material={materials.sandstone} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_19'].geometry} material={materials.sandstone_bottom} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_20'].geometry} material={materials.cut_sandstone} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_21'].geometry} material={materials.MWO_chest_top} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_22'].geometry} material={materials.MWO_chest_side} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_23'].geometry} material={materials.MWO_chest_front} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_24'].geometry} material={materials.MWO_chest_latch} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_25'].geometry} material={materials.light_blue_terracotta} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_26'].geometry} material={materials.dark_prismarine} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_27'].geometry} material={materials.sea_lantern} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_28'].geometry} material={materials['white_concrete.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_29'].geometry} material={materials['black_concrete.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_30'].geometry} material={materials.tall_seagrass_bottom} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_31'].geometry} material={materials.tall_seagrass_top} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_32'].geometry} material={materials.tube_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_33'].geometry} material={materials.brain_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_34'].geometry} material={materials.bubble_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_35'].geometry} material={materials.fire_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_36'].geometry} material={materials.horn_coral_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_37'].geometry} material={materials.tube_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_38'].geometry} material={materials.brain_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_39'].geometry} material={materials.bubble_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_40'].geometry} material={materials.fire_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_41'].geometry} material={materials.horn_coral} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_42'].geometry} material={materials.brain_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_43'].geometry} material={materials.bubble_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_44'].geometry} material={materials.fire_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_45'].geometry} material={materials.horn_coral_fan} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_46'].geometry} material={materials.sea_pickle} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_47'].geometry} material={materials['lantern.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_48'].geometry} material={materials.blackstone_top} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_49'].geometry} material={materials.blackstone} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_50'].geometry} material={materials['copper_ore.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_51'].geometry} material={materials.raw_copper_block} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_52'].geometry} material={materials['glow_lichen.001']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_53'].geometry} material={materials['andesite.005']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_54'].geometry} material={materials['black_concrete.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_55'].geometry} material={materials['coal_ore.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_56'].geometry} material={materials['copper_ore.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_57'].geometry} material={materials['deepslate_top.005']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_58'].geometry} material={materials['deepslate.005']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_59'].geometry} material={materials['diorite.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_60'].geometry} material={materials['dirt.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_61'].geometry} material={materials['granite.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_62'].geometry} material={materials['gravel.008']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_63'].geometry} material={materials['iron_ore.005']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_64'].geometry} material={materials['lantern.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_65'].geometry} material={materials['oak_log.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_66'].geometry} material={materials['oak_log_top.006']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_67'].geometry} material={materials['polished_blackstone_bricks.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_68'].geometry} material={materials['lava_still.004']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_69'].geometry} material={materials['stone.007']} />
        <mesh geometry={nodes['New_World_(8)__9995190_20_3706_to_9995256_170_3864045_70'].geometry} material={materials['white_concrete.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/UnderWaterWhole.glb')
