/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Racw.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Race(props) {
  const { nodes, materials } = useGLTF('/Racw.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[144, -32, 199]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003'].geometry} material={materials.polished_blackstone_bricks} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_1'].geometry} material={materials.terracotta} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_2'].geometry} material={materials.white_concrete} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_3'].geometry} material={materials.black_concrete} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_4'].geometry} material={materials['black_concrete.005']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_5'].geometry} material={materials['black_concrete.006']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_6'].geometry} material={materials['polished_blackstone_bricks.003']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_7'].geometry} material={materials['white_concrete.003']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_8'].geometry} material={materials['black_concrete.003']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_9'].geometry} material={materials['stone.004']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_10'].geometry} material={materials['polished_blackstone_bricks.004']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_11'].geometry} material={materials['white_concrete.004']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_12'].geometry} material={materials['black_concrete.004']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_13'].geometry} material={materials['white_concrete.002']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_14'].geometry} material={materials['black_concrete.002']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_15'].geometry} material={materials['white_concrete.005']} />
        <mesh geometry={nodes['New_World_(8)__9994763_58_4009_to_9994925_319_4093003_16'].geometry} material={materials['white_concrete.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Racw.glb')
