/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/model/xz.glb -o src/components/Model.jsx -k -K -r public 
Author: Gyarmati Zsolt (https://sketchfab.com/zsolt_gyarmati)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/pentagram-medal-5412864c48c14b88bd4da2b1fe97690d
Title: Pentagram Medal
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
export function Model(props) {
  const groupRef = React.useRef()
  const { nodes, materials } = useGLTF('/model/xz.glb')
  useEffect(() => {
    let box = new THREE.Box3().setFromObject(groupRef.current); // 获取模型的包围盒
    let mdlen = box.max.x - box.min.x; // 模型长度
    let mdwid = box.max.z - box.min.z; // 模型宽度
    let mdhei = box.max.y - box.min.y; // 模型高度
    let x1 = box.min.x + mdlen / 2; // 模型中心点坐标X
    let y1 = box.min.y + mdhei / 2; // 模型中心点坐标Y
    let z1 = box.min.z + mdwid / 2; // 模型中心点坐标Z
    groupRef.current.position.set(-x1, -y1, -z1);
  }, [groupRef.current])

  useEffect(() => {
    groupRef.current.traverse((object) => {
      if (object.isMesh) {
        object.castShadow = true
        object.receiveShadow = true
      }
    })
  }, [groupRef.current])

  return (
    <group {...props} ref={groupRef} dispose={null} scale={[0.001, 0.001, 0.001]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="bb73b07926514057bb62f571d964d6d7fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Cylinder" position={[0, 0, 300]} scale={100}>
                <mesh name="Cylinder__0" geometry={nodes.Cylinder__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Cylinder001" position={[0, 271, 300]} scale={100}>
                <mesh name="Cylinder001__0" geometry={nodes.Cylinder001__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Cylinder002" position={[-256, 89, 300]} scale={100}>
                <mesh name="Cylinder002__0" geometry={nodes.Cylinder002__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Cylinder003" position={[-162, -217, 300]} scale={100}>
                <mesh name="Cylinder003__0" geometry={nodes.Cylinder003__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Cylinder004" position={[163, -217, 300]} scale={100}>
                <mesh name="Cylinder004__0" geometry={nodes.Cylinder004__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Cylinder005" position={[256, 88, 300]} scale={100}>
                <mesh name="Cylinder005__0" geometry={nodes.Cylinder005__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Plane" position={[0, 0, 316]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={100}>
                <mesh name="Plane__0" geometry={nodes.Plane__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Plane001" position={[0, 0, 284]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={100}>
                <mesh name="Plane001__0" geometry={nodes.Plane001__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Cylinder007" position={[80, 307, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cylinder007__0" geometry={nodes.Cylinder007__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Cube" position={[0, 340, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube__0" geometry={nodes.Cube__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus002" position={[0, 380, 300]} rotation={[0, Math.PI / 2, 0]} scale={100}>
                <mesh name="Torus002__0" geometry={nodes.Torus002__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Cylinder006" position={[-80, 307, 300]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cylinder006__0" geometry={nodes.Cylinder006__0.geometry} material={materials['Scene_-_Root']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/xz.glb')
