/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/finalRoom.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Office(props) {
  const { nodes, materials } = useGLTF('models/finalRoom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-17.358, 2.106, -20.592]} scale={18.807}>
        <mesh geometry={nodes.Shelf_Small2.geometry} material={materials['White.001']} position={[-0.219, 0.012, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <group position={[30.348, 8.597, 0]} rotation={[0, 1.571, 0]} scale={19.337}>
        <mesh geometry={nodes.ExecutiveChair1.geometry} material={materials.LeatherExecutiveChair1} position={[-0.049, -0.111, -1.041]} rotation={[-Math.PI / 2, 0, 0]} scale={77.559} />
      </group>
    
      <group position={[22.163, 14.648, 27.28]} rotation={[0, 1.571, 0]} scale={-38.686}>
        <mesh geometry={nodes.Computer001.geometry} material={materials['1A1A1A']} position={[-0.026, 0, 0]} scale={100} />
      </group>
      <mesh geometry={nodes.Cube024.geometry} material={materials['FFCC88.003']} position={[0, -0.185, 0]} />
      <group position={[-21.785, 0, 0.097]}>
        <mesh geometry={nodes['Cube_Cube001-Mesh'].geometry} material={materials['1A1A1A']} />
        <mesh geometry={nodes['Cube_Cube001-Mesh_1'].geometry} material={materials['78909C']} />
      </group>
      <group position={[-1, -0.305, 0]} scale={[0.99, 1, 1]}>
        <mesh geometry={nodes['Plane-Mesh'].geometry} material={materials['FFEB3B.002-2']} />
        <mesh geometry={nodes['Plane-Mesh_1'].geometry} material={materials['795548.004-2']} />
      </group>
      <mesh geometry={nodes.Desk.geometry} material={materials['795548.004-2']} position={[23.459, 1.706, -5.468]} rotation={[0, -Math.PI / 2, 0]} scale={2400.255} />
      <mesh geometry={nodes.Monitor.geometry} material={materials['1A1A1A']} position={[27.315, 11.827, 0.597]} rotation={[0, -1.571, 0]} scale={0.041} />
      <group position={[-20.298, 6.248, 0.009]} scale={23.473}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials['mat23.001']} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials['mat17.001']} />
        <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials['mat16.001']} />
        <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat20} />
      </group>
      <group position={[20.837, 12.433, -9.251]} rotation={[3.095, Math.PI / 2, 0]} scale={[1147.81, 1147.811, 1147.81]}>
        <mesh geometry={nodes.Phone_1.geometry} material={materials['White.002']} />
        <mesh geometry={nodes.Phone_2.geometry} material={materials['Grey.001']} />
        <mesh geometry={nodes.Phone_3.geometry} material={materials.Black} />
      </group>
      <mesh geometry={nodes.Comp_Mouse.geometry} material={materials['1A1A1A']} position={[20.759, 12.121, 4.662]} rotation={[0, Math.PI / 2, 0]} scale={0.046} />
      <mesh geometry={nodes.group425587018.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group311988427.geometry} material={materials['mat22.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group96314515.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group449779970.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group2106755496.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1753917514.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1529968652.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group252681800.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1581414308.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group295085766.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group384612072.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group150579309.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1675960081.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group287159489.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1956214489.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group196400395.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group954813675.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group706802639.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1976194690.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1152190519.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group2074153597.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1629609685.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1030983910.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group145618305.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group826580911.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group601803475.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1589752359.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group806343109.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1238060299.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group801095923.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group418912012.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group205302596.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1323238240.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1571332333.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group34220672.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1272091893.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1899843208.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group42243725.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group2146178072.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1316349499.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1754683637.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group475225180.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group77921105.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group96968687.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group268332703.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group993315105.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1740918352.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group588539140.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group729811280.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group573547017.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1180881246.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group687259746.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group45382983.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1149852049.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group790925258.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group873458270.geometry} material={materials['mat21.001']} position={[21.234, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group616518658.geometry} material={materials['mat21.001']} position={[21.234, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group2085389804.geometry} material={materials['mat21.001']} position={[21.234, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1075691498.geometry} material={materials['mat21.001']} position={[21.234, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group2091112366.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1764140354.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1238428394.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group873558583.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1486350934.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1629393722.geometry} material={materials['mat21.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group1870575723.geometry} material={materials['mat16.002']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <mesh geometry={nodes.group877249531.geometry} material={materials['mat9.001']} position={[21.27, 12.34, -1.826]} rotation={[0, -1.549, 0]} scale={4.095} />
      <group position={[31.428, 1.501, -23.602]} scale={36.43}>
        <mesh geometry={nodes.lampRoundFloor_2.geometry} material={materials.metal} />
        <mesh geometry={nodes.lampRoundFloor_2_1.geometry} material={materials.lamp} />
      </group>
      <group position={[31.428, 0, -23.602]} scale={36.43}>
        <mesh geometry={nodes.lampRoundFloor_3.geometry} material={materials.lamp} />
        <mesh geometry={nodes.lampRoundFloor_3_1.geometry} material={materials.metal} />
      </group>
      <mesh geometry={nodes.Computer.geometry} material={materials['Material.002']} scale={100} />
    </group>
  )
}

useGLTF.preload('models/finalRoom.glb')
